"use client"

// Generated by scripts/funnels/new-package.mjs. Do not edit by hand.
import OfferVariant0 from "./app-value-stack"
import OfferVariant1 from "./default"
import OfferVariant2 from "./social-proof-below"

export const OFFER_VARIANTS = {
  "app-value-stack": OfferVariant0,
  default: OfferVariant1,
  "social-proof-below": OfferVariant2,
} as const
